export const PARTY_COLORS = new Map([
  ['CDU', 'black'],
  ['CDU/CSU', 'black'],
  ['CSU', 'black'],
  ['SPD', 'red'],
  ['BUNDNIS90/DIEGRUNEN', 'green'],
  ['DIELINKE', 'purple'],
  ['FDP', 'gold'],
  ['FDP/DVP', 'gold'],
  ['AFD', 'blue'],
  ['PIRATEN', 'orange'],
  ['NPD', 'brown'],
  ['FW', 'gray'],
  ['BVB/FW', 'gray'],
  ['SSW', 'lightgray'],
]);

export const SORTED_PARTIES = [
  'NPD',
  'AFD',
  'FW',
  'FREIEWAHLER',
  'BVB/FW',
  'FDP',
  'FDP/DVP',
  'CDU',
  'CDU/CSU',
  'CSU',
  'BUNDNIS90/DIEGRUNEN',
  'SPD',
  'PIRATEN',
  'SSW',
  'DIELINKE',
];

export const PARTY_NAMES = new Map([
  ['CDU', 'CDU'],
  ['CDU/CSU', 'CDU/CSU'],
  ['CSU', 'CSU'],
  ['SPD', 'SPD'],
  ['BUNDNIS90/DIEGRUNEN', 'Grüne'],
  ['DIELINKE', 'Linke'],
  ['FDP', 'FDP'],
  ['FDP/DVP', 'FDP/DVP'],
  ['AFD', 'AfD'],
  ['PIRATEN', 'Piraten'],
  ['NPD', 'NPD'],
  ['FW', 'FW'],
  ['FREIEWAHLER', 'Freie Wähler'],
  ['BVB/FW', 'BVB/FW'],
  ['SSW', 'SSW'],
]);
